name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  check-formatting:
    name: Check formatting
    uses: khulnasoft/workflows/.github/workflows/lint.yml@main
    secrets: inherit
