name: Synchronize DB
on:
  workflow_dispatch:
permissions:
  actions: read
jobs:
  synchronize-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Aikit 🛎
        uses: actions/checkout@v3
        with:
          path: aikit
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 1

      - name: Synchronize DB
        run: |
          pip install pymongo
          cd aikit
          python scripts/setup_tests/synchronize_db.py ${{ secrets.MONGODB_PASSWORD }}
