name: test-aikit-cron
on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'
permissions:
  actions: read
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Aikit
        uses: actions/checkout@v2
        with:
          path: aikit
          persist-credentials: false
          submodules: "recursive"

      - name: Install aikit and fetch binaries
        run: |
          cd aikit
          pip3 install -e .
          mkdir .aikit
          touch .aikit/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .aikit/key.pem
          cd ..

      - name: Get Job URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Run Tests
        id: tests
        run: |
          cd aikit
          pip3 install pymongo
          python scripts/setup_tests/cron_tests.py ${{ github.run_number }} false
          python scripts/run_tests/run_tests.py ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD }} ${{ secrets.MONGODB_PASSWORD }} 'false' 'false' ${{ github.run_id }} 'false' ${{ steps.jobs.outputs.html_url }}
        continue-on-error: true

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
